### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by adranwit** [alexbrainman/odbc#138]
Seeing intermittently unexpected signal during runtime execution

Here is stack trace:

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7ff4ffffffff pc=0x7ff52f75ecc0]
 
runtime stack:
runtime.throw(0xda1b7f, 0x2a)
     /usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
     /usr/local/go/src/runtime/signal_unix.go:374 +0x4a9
 
goroutine 94503 [syscall]:
runtime.cgocall(0xb7a650, 0xc000a45160, 0x0)
     /usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc000a45130 sp=0xc000a450f8 pc=0x40700b
github.com/alexbrainman/odbc/api._Cfunc_SQLDriverConnectW(0x7ff4c401a310, 0x0, 0xc000714000, 0xfffd, 0x0, 0x0, 0x0, 0x0, 0xc000a40000)
     _cgo_gotypes.go:312 +0x4c fp=0xc000a45160 sp=0xc000a45130 pc=0x8a190c
github.com/alexbrainman/odbc/api.SQLDriverConnect.func1(0x7ff4c401a310, 0x0, 0xc000714000, 0x70fffd, 0x0, 0x0, 0x0, 0xc000710000, 0x5f)
     /root/go/pkg/mod/github.com/alexbrainman/odbc@v0.0.0-20190102080306-cf37ce290779/api/zapi_unix.go:59 +0xe1 fp=0xc000a451c0 sp=0xc000a45160 pc=0x8a33f1
github.com/alexbrainman/odbc/api.SQLDriverConnect(0x7ff4c401a310, 0x0, 0xc000714000, 0xc00071fffd, 0x0, 0x0, 0x0, 0xc000a40000, 0x40fd09)
     /root/go/pkg/mod/github.com/alexbrainman/odbc@v0.0.0-20190102080306-cf37ce290779/api/zapi_unix.go:59 +0x7e fp=0xc000a45218 sp=0xc000a451c0 pc=0x8a287e
github.com/alexbrainman/odbc.(*Driver).Open(0x16d1840, 0xc00089cf60, 0x5e, 0x0, 0x0, 0x0, 0x0)
     /root/go/pkg/mod/github.com/alexbrainman/odbc@v0.0.0-20190102080306-cf37ce290779/conn.go:34 +0x1ab fp=0xc000a45328 sp=0xc000a45218 pc=0x8a678b
database/sql.dsnConnector.Connect(...)
     /usr/local/go/src/database/sql/sql.go:636

**Comment by alexbrainman** [comment]
> Seeing intermittently unexpected signal during runtime execution
> 
> Here is stack trace:

Sorry. But I don't know what the problem is.

Perhaps, if you provide steps to reproduce this, I might help. I will need to know as much as possible about your OS, version of Go you used to compile the program, database you used (including all appropriate settings), the driver you used (including all appropriate settings), and small program that crashes for you.

Alex

Alex

**Comment by TestMsr** [comment]
> > Seeing intermittently unexpected signal during runtime execution
> > Here is stack trace:
> 
> Sorry. But I don't know what the problem is.
> 
> Perhaps, if you provide steps to reproduce this, I might help. I will need to know as much as possible about your OS, version of Go you used to compile the program, database you used (including all appropriate settings), the driver you used (including all appropriate settings), and small program that crashes for you.
> 
> Alex
> 
> Alex

i have the same problem 
i found when err occurs
it doesnt print log and crashed in my server
but in my local enviroment and virtulmachine it works ok

go ver 1.12
server :Linux  4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
local:win10
virtualmachine:Linux testmsr-Virtual-Machine 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
database:shentongdata.com
using github.com/jinzhu/gorm

`
runtime stack:
runtime.throw(0xe59616, 0x2a)
	/usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x4a9

goroutine 1 [syscall]:
runtime.cgocall(0xc137f0, 0xc00067f160, 0x200000003)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc00067f130 sp=0xc00067f0f8 pc=0x40557b
/server/vendor/github.com/alexbrainman/odbc/api._Cfunc_SQLNumParams(0x7f92580008c0, 0xc000432e4c, 0x0)
	_cgo_gotypes.go:438 +0x4c fp=0xc00067f160 sp=0xc00067f130 pc=0x82b7ac
/server/vendor/github.com/alexbrainman/odbc/api.SQLNumParams.func1(0x7f92580008c0, 0xc000432e4c, 0xc000432e4e)
/server/vendor/github.com/alexbrainman/odbc/api/zapi_unix.go:94 +0x60 fp=0xc00067f198 sp=0xc00067f160 pc=0x82d020
`

**Comment by alexbrainman** [comment]
> i have the same problem

I am sorry to hear that.

> i found when err occurs
> it doesnt print log and crashed in my server
> but in my local enviroment and virtulmachine it works ok

That information does not give me any clues. Sorry.

> go ver 1.12
> server :Linux 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
> local:win10
> virtualmachine:Linux testmsr-Virtual-Machine 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
> database:shentongdata.com
> using github.com/jinzhu/gorm

This information won't be enough to even attempt to reproduce your problem. See https://github.com/alexbrainman/odbc/issues/138#issuecomment-502333051 for more details.

Alex
