### ISSUE TITLE
Test fails on RedHat Linux 5.9 with unixODBC 2.3.1 and FreeTDS 0.91RC2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [alexbrainman/odbc#25]
```
What steps will reproduce the problem?
1. Install freetds package with 'yum install'
2. Compile unixODBC 2.3.1 from source
3. Install the package with "go get code.google.com/p/odbc"
4. Run test with go test -mssrv SERVER -msuser USER -mspass PASSWD -msdb DB

What is the expected output? 

All tests pass

What do you see instead?

I see the following runtime error:

panic: runtime error: slice bounds out of range [recovered]
    panic: runtime error: slice bounds out of range

goroutine 4 [running]:
testing.func·004()
    /usr/local/src/go/src/pkg/testing/testing.go:348 +0xcd
code.google.com/p/odbc.(*BindableColumn).Value(0xc200070e40, 0x6b6c050, 0x6, 
0x4f36c0, 0xc200087cc0, ...)
    /home/oracle/gosrc/src/code.google.com/p/odbc/column.go:239 +0x283
code.google.com/p/odbc.(*Rows).Next(0xc2000004c8, 0xc200054540, 0x7, 0x7, 
0x54ee20, ...)
    /home/oracle/gosrc/src/code.google.com/p/odbc/rows.go:34 +0x137
database/sql.(*Rows).Next(0xc20008a300, 0x3)
    /usr/local/src/go/src/pkg/database/sql/sql.go:1310 +0xc1
code.google.com/p/odbc.TestMSSQLCreateInsertDelete(0xc200098000)
    /home/oracle/gosrc/src/code.google.com/p/odbc/mssql_test.go:270 +0x62f
testing.tRunner(0xc200098000, 0x815780)
    /usr/local/src/go/src/pkg/testing/testing.go:353 +0x8a
created by testing.RunTests
    /usr/local/src/go/src/pkg/testing/testing.go:433 +0x86b

goroutine 1 [chan receive]:
testing.RunTests(0x583330, 0x815780, 0xf, 0xf, 0x1, ...)
    /usr/local/src/go/src/pkg/testing/testing.go:434 +0x88e
testing.Main(0x583330, 0x815780, 0xf, 0xf, 0x824580, ...)
    /usr/local/src/go/src/pkg/testing/testing.go:365 +0x8a
main.main()
    code.google.com/p/odbc/_test/_testmain.go:73 +0x9a

goroutine 2 [syscall]:
exit status 2
FAIL    code.google.com/p/odbc  0.101s

What version of the product are you using? On what operating system?

[oracle@custservices odbc]$ go version
go version go1.1.2 linux/amd64
[oracle@custservices odbc]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 5.9 (Tikanga)
[oracle@custservices odbc]$ uname -a
Linux custservices 2.6.18-348.3.1.el5 #1 SMP Tue Mar 5 13:19:32 EST 2013 x86_64 
x86_64 x86_64 GNU/Linux

Please provide any additional information below.

```

Original issue reported on code.google.com by `victor.kryukov` on 12 Nov 2013 at 2:54

**Comment by watercraft** [comment]
I see a similar panic.  Note that c.Len is no ware near -1 or MAXINT and my environment is 64 bit.
```
ALAN 259 len buffer 256 len 324
2018/11/02 11:13:36 http2: panic serving 172.26.0.1:57406: runtime error: slice bounds out of range
goroutine 54 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc4202da000, 0xc4203b5faf, 0xc420020380)
	/usr/lib/go-1.10/src/net/http/h2_bundle.go:5753 +0x190
panic(0x7f7e20, 0xc8eec0)
	/usr/lib/go-1.10/src/runtime/panic.go:502 +0x229
bitbucket.eng.zebrium.com/zsw/zwsd/vendor/github.com/alexbrainman/odbc.(*BindableColumn).Value(0xc4205afa80, 0x7f76c00008c0, 0x61, 0x7cf2e0, 0xc4204031e8, 0x0, 0x0)
	/home/alan-y/go/src/bitbucket.eng.zebrium.com/zsw/zwsd/vendor/github.com/alexbrainman/odbc/column.go:260 +0x3e7
bitbucket.eng.zebrium.com/zsw/zwsd/vendor/github.com/alexbrainman/odbc.(*Rows).Next(0xc4202da018, 0xc4200a9800, 0x62, 0x62, 0x0, 0xc4203b4408)
	/home/alan-y/go/src/bitbucket.eng.zebrium.com/zsw/zwsd/vendor/github.com/alexbrainman/odbc/rows.go:35 +0xbf
database/sql.(*Rows).nextLocked(0xc4202ece00, 0xc420320000)
	/usr/lib/go-1.10/src/database/sql/sql.go:2622 +0xc4
database/sql.(*Rows).Next.func1()
	/usr/lib/go-1.10/src/database/sql/sql.go:2600 +0x3c
database/sql.withLock(0x8c8a00, 0xc4202ece30, 0xc4203b4458)
	/usr/lib/go-1.10/src/database/sql/sql.go:3032 +0x63
database/sql.(*Rows).Next(0xc4202ece00, 0xc4202da130)
	/usr/lib/go-1.10/src/database/sql/sql.go:2599 +0x7a
bitbucket.eng.zebrium.com/zsw/zwsd/link.EventMapAction(0xc42016e630, 0xc4205a6900, 0xc4202ce5c0, 0x873877, 0x10)
	/home/alan-y/go/src/bitbucket.eng.zebrium.com/zsw/zwsd/link/event_map.go:179 +0x3069
bitbucket.eng.zebrium.com/zsw/zwsd/zwsd/handlers/eventmap.EventMapAPI.Post(0xc42016e630)
	/home/alan-y/go/src/bitbucket.eng.zebrium.com/zsw/zwsd/zwsd/handlers/eventmap/eventmap_api_Map.go:37 +0x234
main.(EventMapInterface).Post-fm(0xc42016e630)
	/home/alan-y/go/src/bitbucket.eng.zebrium.com/zsw/zwsd/zwsd/eventmap_if.go:19 +0x39
bitbucket.eng.zebrium.com/zsw/zwsd/link.TokenAuthHandler.ServeHTTP(0xc420162620, 0x8c9b40, 0xc4202da000, 0xc420142700)
	/home/alan-y/go/src/bitbucket.eng.zebrium.com/zsw/zwsd/link/auth.go:145 +0x8f9
bitbucket.eng.zebrium.com/zsw/zwsd/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201607e0, 0x8c9b40, 0xc4202da000, 0xc420142700)
	/home/alan-y/go/src/bitbucket.eng.zebrium.com/zsw/zwsd/vendor/github.com/gorilla/mux/mux.go:162 +0xed
bitbucket.eng.zebrium.com/zsw/zwsd/vendor/github.com/watercraft/handlers.(*cors).ServeHTTP(0xc4201d6120, 0x8c9b40, 0xc4202da000, 0xc420364100)
	/home/alan-y/go/src/bitbucket.eng.zebrium.com/zsw/zwsd/vendor/github.com/watercraft/handlers/cors.go:51 +0xa04
net/http.serverHandler.ServeHTTP(0xc4201de000, 0x8c9b40, 0xc4202da000, 0xc420364100)
	/usr/lib/go-1.10/src/net/http/server.go:2694 +0xbc
net/http.initNPNRequest.ServeHTTP(0xc4200f8a80, 0xc4201de000, 0x8c9b40, 0xc4202da000, 0xc420364100)
	/usr/lib/go-1.10/src/net/http/server.go:3260 +0x9a
net/http.(Handler).ServeHTTP-fm(0x8c9b40, 0xc4202da000, 0xc420364100)
	/usr/lib/go-1.10/src/net/http/h2_bundle.go:5475 +0x4d
net/http.(*http2serverConn).runHandler(0xc420020380, 0xc4202da000, 0xc420364100, 0xc42000c080)
	/usr/lib/go-1.10/src/net/http/h2_bundle.go:5760 +0x89
created by net/http.(*http2serverConn).processHeaders
	/usr/lib/go-1.10/src/net/http/h2_bundle.go:5494 +0x46b
```

**Comment by alexbrainman** [comment]
> bitbucket.eng.zebrium.com/zsw/zwsd/vendor/github.com/alexbrainman/odbc.(*BindableColumn).Value(0xc4205afa80, 0x7f76c00008c0, 0x61, 0x7cf2e0, 0xc4204031e8, 0x0, 0x0) /home/alan-y/go/src/bitbucket.eng.zebrium.com/zsw/zwsd/vendor/github.com/alexbrainman/odbc/column.go:260 +0x3e7

Current version of column.go line 260 https://github.com/alexbrainman/odbc/blob/2d7d0e45c7870320611501683ca6073a0d9dfeed/column.go#L260 does not have panic. And you did not say how do I reproduce the problem.

Alex
